# Dockerfile
FROM node:18-alpine

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production

COPY app.js ./

# Porti ku do të dëgjojë
EXPOSE 3000

# Komanda për nisjen e serverit
CMD ["npm", "start"]
